// <auto-generated />
using AIS_N3_Plavec_Alen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIS_N3_Plavec_Alen.Migrations
{
    [DbContext(typeof(TrgovinaContext))]
    partial class TrgovinaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("AIS_N3_Plavec_Alen.Models.Dobavitelj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kontakt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Naziv");

                    b.ToTable("Dobavitelji");
                });

            modelBuilder.Entity("AIS_N3_Plavec_Alen.Models.Izdelek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0.0m);

                    b.Property<string>("Kategorija")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Naziv");

                    b.ToTable("Izdelki");
                });

            modelBuilder.Entity("AIS_N3_Plavec_Alen.Models.IzdelekDobavitelj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DobaviteljId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IzdelekId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KolicinaNaZalogi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DobaviteljId");

                    b.HasIndex("IzdelekId");

                    b.ToTable("IzdelekDobavitelji");
                });

            modelBuilder.Entity("AIS_N3_Plavec_Alen.Models.IzdelekDobavitelj", b =>
                {
                    b.HasOne("AIS_N3_Plavec_Alen.Models.Dobavitelj", "Dobavitelj")
                        .WithMany("IzdelekDobavitelji")
                        .HasForeignKey("DobaviteljId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AIS_N3_Plavec_Alen.Models.Izdelek", "Izdelek")
                        .WithMany("IzdelekDobavitelji")
                        .HasForeignKey("IzdelekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dobavitelj");

                    b.Navigation("Izdelek");
                });

            modelBuilder.Entity("AIS_N3_Plavec_Alen.Models.Dobavitelj", b =>
                {
                    b.Navigation("IzdelekDobavitelji");
                });

            modelBuilder.Entity("AIS_N3_Plavec_Alen.Models.Izdelek", b =>
                {
                    b.Navigation("IzdelekDobavitelji");
                });
#pragma warning restore 612, 618
        }
    }
}
